export const category = [

  {
    seccion:"populares",
    lista:[
      {
        nombre:"Batido dulce de leche",
        comentario:"Orgullo argentino",
        img:'img/dulce-de-leche.jpg',
        precio:80
      },
      {
        nombre:"Chocolate con helado",
        comentario:"Clasico",
        img:'img/chocolate-helado.jpg',
        precio:250
      },
      {
        nombre:"",
        comentario:"",
        img:'img/.jpg',
        precio:80
      },
      {
        nombre:"",
        comentario:"",
        img:'img/.jpg',
        precio:80
      },
      {
        nombre:"",
        comentario:"",
        img:'img/.jpg',
        precio:80
      },
      {
        nombre:"",
        comentario:"",
        img:'img/.jpg',
        precio:80
      },
      {
        nombre:"",
        comentario:"",
        img:'img/.jpg',
        precio:80
      },
      {
        nombre:"",
        comentario:"",
        img:'img/.jpg',
        precio:80
      },
    ]
  },

  {
    seccion:"pizzas",
    lista:[
      {
        nombre:"",
        comentario:"",
        img:'img/.jpg',
        precio:80
      },
      {
        nombre:"",
        comentario:"",
        img:'img/.jpg',
        precio:80
      },
      {
        nombre:"",
        comentario:"",
        img:'img/.jpg',
        precio:80
      },
      {
        nombre:"",
        comentario:"",
        img:'img/.jpg',
        precio:80
      },
      {
        nombre:"",
        comentario:"",
        img:'img/.jpg',
        precio:80
      },
      {
        nombre:"",
        comentario:"",
        img:'img/.jpg',
        precio:80
      },
      {
        nombre:"",
        comentario:"",
        img:'img/.jpg',
        precio:80
      },
      {
        nombre:"",
        comentario:"",
        img:'img/.jpg',
        precio:80
      }
    ]
  },

  {
    seccion:"hamburguesas",
    lista:[
      {
        nombre:"",
        comentario:"",
        img:'img/.jpg',
        precio:80
      },
      {
        nombre:"",
        comentario:"",
        img:'img/.jpg',
        precio:80
      },
      {
        nombre:"",
        comentario:"",
        img:'img/.jpg',
        precio:80
      },
      {
        nombre:"",
        comentario:"",
        img:'img/.jpg',
        precio:80
      },
      {
        nombre:"",
        comentario:"",
        img:'img/.jpg',
        precio:80
      },
      {
        nombre:"",
        comentario:"",
        img:'img/.jpg',
        precio:80
      },
      {
        nombre:"",
        comentario:"",
        img:'img/.jpg',
        precio:80
      },
      {
        nombre:"",
        comentario:"",
        img:'img/.jpg',
        precio:80
      }
    ]
  },

  {
    seccion:"papas fritas",
    lista:[
      {
        nombre:"",
        comentario:"",
        img:'img/.jpg',
        precio:80
      },
      {
        nombre:"",
        comentario:"",
        img:'img/.jpg',
        precio:80
      },
      {
        nombre:"",
        comentario:"",
        img:'img/.jpg',
        precio:80
      },
      {
        nombre:"",
        comentario:"",
        img:'img/.jpg',
        precio:80
      },
      {
        nombre:"",
        comentario:"",
        img:'img/.jpg',
        precio:80
      },
      {
        nombre:"",
        comentario:"",
        img:'img/.jpg',
        precio:80
      },
      {
        nombre:"",
        comentario:"",
        img:'img/.jpg',
        precio:80
      },
      {
        nombre:"",
        comentario:"",
        img:'img/.jpg',
        precio:80
      }
    ]
  },

  {
    seccion:"wraps",
    lista:[
      {
        nombre:"",
        comentario:"",
        img:'img/.jpg',
        precio:80
      },
      {
        nombre:"",
        comentario:"",
        img:'img/.jpg',
        precio:80
      },
      {
        nombre:"",
        comentario:"",
        img:'img/.jpg',
        precio:80
      },
      {
        nombre:"",
        comentario:"",
        img:'img/.jpg',
        precio:80
      },
      {
        nombre:"",
        comentario:"",
        img:'img/.jpg',
        precio:80
      },
      {
        nombre:"",
        comentario:"",
        img:'img/.jpg',
        precio:80
      },
      {
        nombre:"",
        comentario:"",
        img:'img/.jpg',
        precio:80
      },
      {
        nombre:"",
        comentario:"",
        img:'img/.jpg',
        precio:80
      }
    ]
  },

  {
    seccion:"mexican food",
    lista:[
      {
        nombre:"",
        comentario:"",
        img:'img/.jpg',
        precio:80
      },
      {
        nombre:"",
        comentario:"",
        img:'img/.jpg',
        precio:80
      },
      {
        nombre:"",
        comentario:"",
        img:'img/.jpg',
        precio:80
      },
      {
        nombre:"",
        comentario:"",
        img:'img/.jpg',
        precio:80
      },
      {
        nombre:"",
        comentario:"",
        img:'img/.jpg',
        precio:80
      },
      {
        nombre:"",
        comentario:"",
        img:'img/.jpg',
        precio:80
      },
      {
        nombre:"",
        comentario:"",
        img:'img/.jpg',
        precio:80
      },
      {
        nombre:"",
        comentario:"",
        img:'img/.jpg',
        precio:80
      }
    ]
  },

  {
    seccion:"batidos",
    lista:[
      {
        nombre:"Fresa y platano",
        comentario:"Combinacion dulce",
        img:'img/fresa-platano.jpg',
        precio:300
      },
      {
        nombre:"Tres frutos rojos",
        comentario:"Aguante el rojo",
        img:'img/frutos-rojos.jpg',
        precio:80
      },
      {
        nombre:"Batido Tropical",
        comentario:"Suave",
        img:'img/tropical.jpg',
        precio:150
      },
      {
        nombre:"Batido de mango",
        comentario:"Welinton campeón",
        img:'img/mango.jpg',
        precio:400
      },
      {
        nombre:"Chocolate con helado",
        comentario:"Clasico",
        img:'img/chocolate-helado.jpg',
        precio:250
      },
      {
        nombre:"Batido de nutella",
        comentario:"Amante del sabor",
        img:'img/nutella.jpg',
        precio:100
      },
      {
        nombre:"Chocolate vegano",
        comentario:"Sabor unico",
        img:'img/vegano.jpg',
        precio:60
      },
      {
        nombre:"Batido dulce de leche",
        comentario:"Orgullo argentino",
        img:'img/dulce-de-leche.jpg',
        precio:80
      }
    ]
  },

]
